namnt/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('hello_world', 'HelloWorldController@show');
Route::resource('users', 'UserController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

namnt/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;


class User extends Authenticatable
{
    use SoftDeletes;

    const ROLE_ADMIN = 1;
    const ROLE_STAFF = 2;

    public static $role = [
        self::ROLE_ADMIN => 'Quản trị viên',
        self::ROLE_STAFF => 'Nhân viên',
    ];

    protected $dates = ['deleted_at'];
    protected $table = 'users';
    protected $fillable = ['mail_address', 'password', 'name', 'address', 'phone', 'role'];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function getList(array $data)
    {
        $builder = User::orderBy('mail_address', 'ASC');

        if (isset($data['mail_address']) && $data['mail_address'] != '') {
            $builder->where('mail_address', 'like', '%' . $data['mail_address'] . '%');
        }

        if (isset($data['name']) && $data['name'] != '') {
            $builder->where('name', 'like', '%' . $data['name'] . '%');
        }

        if (isset($data['address']) && $data['address'] != '') {
            $builder->where('address', 'like', '%' . $data['address'] . '%');
        }

        if (isset($data['phone']) && $data['phone'] != '') {
            $builder->where('phone', $data['phone']);
        }
        return $builder->paginate(20);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function createUser(array $data)
    {
        $data['password'] = bcrypt($data['password']);
        return User::create($data);
    }
}

namnt/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

namnt/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

namnt/app/Http/Controllers/HelloWorldController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HelloWorldController extends Controller
{
    public function show()
    {
        return view('hello_world.show');
    }
}

namnt/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

namnt/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Requests\CreateUserRequest;
use App\Jobs\SendRegisterEmail;


class UserController extends Controller
{
    protected $user;
    protected $role;


    /**
     * Create a new controller instance.
     *
     * @param User $users
     * @return void
     */
    public function __construct(User $user)
    {
        $this->user = $user;
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = $this->user->getList($request->all());
        $this->authorize('staff');
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('admin');
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $user = $this->user->createUser($request->all());
        SendRegisterEmail::dispatch($user);
        flash('Thêm mới người dùng thành công')->success();
        return redirect()->route('users.index');
    }
}

namnt/resources/views/hello_world/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Xin chào </h1>
</body>
</html>

namnt/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

namnt/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

namnt/resources/views/layouts/default.blade.php
<!doctype html>
<html lang="en">
    @include('layouts.head')
<body>
<div class="container">
    @include('layouts.header')
        @yield('content')
    @include('layouts.footer')
</div>
</body>
</html>

namnt/resources/views/layouts/footer.blade.php
<footer>
    <p class="text-center">PHP training by LIFETIME technologies</p>
</footer>

namnt/resources/views/layouts/head.blade.php
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<title>@yield('title')</title>
</head>

namnt/resources/views/layouts/header.blade.php
@section('header')
    <h1> @yield('title') </h1>
@show

namnt/resources/views/users/create.blade.php
@extends('layouts.default')
@section('title', 'Thêm mới người dùng')
@section('content')
<div class="container-fluid">
    @include('flash::message')
    <div class="row">
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
            <table>
            <form action="{{ route('users.store') }}" method="POST" >
            <input name="_token" type="hidden" value="{{ csrf_token() }}"/>
                <tr>
                    <div class="form-group" >
                    <td><label  @if ($errors->first('mail_address')) style="color:red" @endif >Email</label></td>
                    <td>
                        <input @if ($errors->first('mail_address')) style="border-color:red" @endif type="text" name="mail_address" class="form-control" placeholder="Nhập mail..."  }}">
                        @if ($errors->first('mail_address'))
                            <span style="color: red">{{ $errors->first('mail_address') }}</span>
                        @endif
                    </td>
                </tr>
                <tr>
                    <div class="form-group" >
                        <td><label @if ($errors->first('password')) style="color:red" @endif >Mật khẩu</label></td>
                        <td>
                            <input @if ($errors->first('password')) style="border-color:red" @endif type="password" name="password" class="form-control"  id="exampleInputPassword1" placeholder="Mật khẩu" >
                            @if ($errors->first('password'))
                                <span style="color: red">{{ $errors->first('password') }}</span>
                            @endif
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-group">
                        <td><label @if ($errors->first('password_confirmation')) style="color:red" @endif >Mật khẩu xác nhận</label></td>
                        <td>
                            <input @if ($errors->first('password_confirmation')) style="border-color:red" @endif type="password" name="password_confirmation" class="form-control" id="exampleInputPassword1" placeholder="Mật khẩu xác nhận" >
                            @if ($errors->first('password_confirmation'))
                                <span style="color: red">{{ $errors->first('password_confirmation') }}</span>
                            @endif
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-group">
                        <td><label @if ($errors->first('name')) style="color:red" @endif >Tên</label></td>
                        <td>
                            <input @if ($errors->first('name')) style="border-color:red" @endif type="text" name="name" class="form-control" id="exampleInputPassword1" placeholder="Tên" >
                            @if ($errors->first('name'))
                                <span style="color: red">{{ $errors->first('name') }}</span>
                            @endif
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-group">
                        <td><label @if ($errors->first('address')) style="color:red" @endif >Địa chỉ</label>
                        <td>
                            <input @if ($errors->first('address')) style="border-color:red" @endif type="text" name="address" class="form-control" id="exampleInputPassword1" placeholder="Địa chỉ" >
                            @if ($errors->first('address'))
                                <span style="color: red">{{ $errors->first('address') }}</span>
                            @endif
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-group">
                        <td><label @if ($errors->first('phone')) style="color:red" @endif >Số điện thoại</label>
                        <td>
                            <input @if ($errors->first('phone')) style="border-color:red" @endif type="text" name="phone"   class="form-control" id="exampleInputPassword1" placeholder="0.." >

                            @if ($errors->first('phone'))
                                <span style="color: red">{{ $errors->first('phone') }}</span>
                            @endif
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-group">
                        <td><label for="role">Vai trò người dùng: </label>
                        <td>
                            <div class="form-group">
                                <select class="form-control" id="role" name="role">
                                    @foreach (\App\Models\User::$role as $key => $role)
                                    <option value="{{ $key }}"> {{ $role }} </option>
                                    @endforeach
                                </select>
                            </div>
                        </td>
                    </div>
                </tr>
                <tr>
                    <div class="form-group">
                        <td><a class="btn btn-success btn-sm" href="{{ route('users.index') }}">Quay lại</i></a></td>
                        <td><button type="submit" name="register" class="btn btn-primary">Thêm mới</button></td>
                    </div>
                </tr>
            </form>
            </table>
        </div>
        <div class="col-sm-4">
        </div>
    </div>
</div>
@endsection

namnt/resources/views/users/index.blade.php
@extends('layouts.default')
@section('title', 'Danh sách người dùng')
@section('header')
@section('content')
    <div class="row">
    <table class="col-md-6 col-md-push-3">
        <form action="{{ route('users.index') }}" method="get" >
            <input name="_token" type="hidden" value="{{ csrf_token() }}"/>
            <tr>
                <div class="form-group" >
                    <td><label >Email</label></td>
                    <td>
                        <input type="text" name="mail_address" class="form-control" placeholder="Nhập mail..." >
                    </td>
            </tr>
            <tr>
                <div class="form-group">
                    <td><label>Tên</label></td>
                    <td>
                        <input type="text" name="name" class="form-control" id="exampleInputPassword1" placeholder="Tên" >
                    </td>
                </div>
            </tr>
            <tr>
                <div class="form-group">
                    <td><label>Địa chỉ</label>
                    <td>
                        <input type="text" name="address" class="form-control" id="exampleInputPassword1" placeholder="Địa chỉ" >
                    </td>
                </div>
            </tr>
            <tr>
                <div class="form-group">
                    <td><label>Số điện thoại</label>
                    <td>
                        <input type="text" name="phone"   class="form-control" id="exampleInputPassword1" placeholder="0.." >
                    </td>
                </div>
            </tr><tr>
                <div class="form-group">
                    <td></td>
                    <td><button type="submit" name="submit" class="btn btn-primary">Tìm kiếm</button></td>
                </div>
            </tr>
        </form>
    </table>
    </div>
    @include('flash::message')
    <?php $i = ($users->currentpage()-1)* $users->perpage() + 1;?>
    <table class="table table-striped">
    <thead>
    <tr>
        <th class="text-center">#</th>
        <th class="text-center">Name</th>
        <th class="text-center">Mail</th>
        <th class="text-center">Password</th>
        <th class="text-center">Address</th>
        <th class="text-center">Phone</th>
        <th class="text-center">Role</th>
        <th>
        @can('admin')
            <a href=" {{ route('users.create') }}" class="btn btn-info"> Đăng kí </a> 
        @endcan  
        </th>
    </tr>
    </thead>
    <tbody>
        @foreach ($users as $user)
        <tr>
            <td>{{ $i++ }}</td>
            <td>{{ Helper::toUpperCase($user->name) }}</td>
            <td>{{ $user->mail_address }}</td>
            <td>{{ $user->password }}</td>
            <td>{{ $user->address }}</td>
            <td>{{ $user->phone }}</td>
            <td>
                @if ($user->role === 1) 
                    {{ \App\Models\User::$role['1'] }}
                @elseif ($user->role === 2)
                    {{ \App\Models\User::$role['2'] }}
                @endif
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
<div class="text-center">{!! $users->links() !!}</div>
</div>
@endsection